// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NAS_BAL.EF;

#nullable disable

namespace Nasa_DAL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NAS_BAL.Entities.Meteorite", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Fall")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Mass")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NameType")
                        .HasColumnType("int");

                    b.Property<string>("RecClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Reclat")
                        .HasColumnType("float");

                    b.Property<double>("Reclong")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Year")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Meteorite_Name");

                    b.HasIndex("RecClass")
                        .HasDatabaseName("IX_Meteorite_RecClass");

                    b.HasIndex("Year")
                        .HasDatabaseName("IX_Meteorite_Year");

                    b.ToTable("Meteorites", (string)null);
                });

            modelBuilder.Entity("Nasa_DAL.Entities.Geolocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Coordinates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MeteoriteId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MeteoriteId")
                        .IsUnique();

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Geolocation_Type");

                    b.ToTable("Geolocations", (string)null);
                });

            modelBuilder.Entity("Nasa_DAL.Entities.Geolocation", b =>
                {
                    b.HasOne("NAS_BAL.Entities.Meteorite", "Meteorite")
                        .WithOne("Geolocation")
                        .HasForeignKey("Nasa_DAL.Entities.Geolocation", "MeteoriteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meteorite");
                });

            modelBuilder.Entity("NAS_BAL.Entities.Meteorite", b =>
                {
                    b.Navigation("Geolocation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
